### ISSUE TITLE
Add normalizers for OSISAF data

### ISSUE THREAD

**Issue by akorosov** [nansencenter/metanorm#10]
This is connected to issue in harvesters: https://github.com/nansencenter/django-geo-spaas-harvesting/issues/16

Normalizers for metadata from ingestors (similar to SentinelSAFEMetadataNormalizer) and from Identifier (similar to SentinelOneIdentifierMetadataNormalizer) should be added.

The identifier normalizer should add Parameters:
standard_name = sea_ice_area_fraction

It is important to keep in mid extendability to add more sources of data and more parameters from OSISAF.

**Comment by akorosov** [comment]
Raw metadata from MET OSISAF:
https://thredds.met.no/thredds/dodsC/osisaf/met.no/ice/amsr2_conc/2020/07/ice_conc_nh_polstere-100_amsr2_202007121200.nc.ddx

**Comment by akorosov** [comment]
After sea ice concentration normalizers for sea ice type and sea ice drift should be added
Parameters:
sea_ice_x_displacement
sea_ice_y_displacement

sea_ice_classification

**Comment by aanersc** [comment]
Everything needed is written in a3466b7 except parameter assignment. I need the start name of parameters for it. Please provide them for me @akorosov .

**Comment by akorosov** [comment]
@aanersc , I already wrote these names. See above.

**Comment by aanersc** [comment]
@aperrin66 
Please have a look at this new normalizer, If you agree with in general, then I start to write some tests for it. Find it in 7849bf9 please.

**Comment by aanersc** [comment]
Dear @akorosov,

PLease check out the new normalizer of OSISAF from remote sensing point of view in order to deliver meaningfull results in 'get_platform' and 'get_instrument' methods of it. It is necessary to mention this aspect of work.

**Comment by akorosov** [comment]
For all products you can use:
pti.get_gcmd_platform('Earth Observation Satellites')     

And these instruments:

https://thredds.met.no/thredds/catalog/osisaf/met.no/ice/conc/catalog.html
pti.get_gcmd_instrument('Imaging Spectrometers/Radiometers')    

https://thredds.met.no/thredds/catalog/osisaf/met.no/ice/amsr2_conc/catalog.html
pti.get_gcmd_instrument('AMSR2') 

https://thredds.met.no/thredds/catalog/osisaf/met.no/ice/drift_lr/merged/catalog.html
pti.get_gcmd_instrument('Earth Remote Sensing Instruments')

https://thredds.met.no/thredds/catalog/osisaf/met.no/ice/drift_mr/catalog.html
pti.get_gcmd_instrument('AVHRR')    

https://thredds.met.no/thredds/catalog/osisaf/met.no/ice/edge/catalog.html
pti.get_gcmd_instrument('Imaging Spectrometers/Radiometers')    

https://thredds.met.no/thredds/osisaf/osisaf_seaicetype.html
pti.get_gcmd_instrument('Imaging Spectrometers/Radiometers')
