### ISSUE TITLE
Sometime the get_dataset_parameter returns None!

### ISSUE THREAD

**Issue by aanersc** [nansencenter/metanorm#21]
I think it is good to augment the code in this line:
https://github.com/nansencenter/metanorm/blob/d09a2908f8b4487e579c77b3652fc1d44b774bb6/metanorm/normalizers/base.py#L75
to be modifed as:
```python
                new_members = getattr(self, 'get_' + param)(raw_attributes) or []
```

The reason is that if the get_dataset_parameter does not return anything in any normalizer, then the `new_member` becomes None and this causes error in the next line:
https://github.com/nansencenter/metanorm/blob/d09a2908f8b4487e579c77b3652fc1d44b774bb6/metanorm/normalizers/base.py#L76
and raise an error during the harvesting process.

So for the safety of harvesting process, I think it is good to give it second chance to be `[]` by using python `or` so that the Nonetype error is never raise!

I have seen this error when I accidentaly wrote the incorrect  `get_dataset_parameter` which gives `None` sometimes!

What is your feedback @aperrin66 ?

**Comment by aperrin66** [comment]
We should not hide this kind of error, otherwise mistakes in get_... methods might escape our notice.
