### ISSUE TITLE
SentinelOneIdentifier should also return Parameters

### ISSUE THREAD

**Issue by akorosov** [nansencenter/metanorm#9]
* To add get_parameters() method which returns a list with one entry:
```python
return [pti.get_wkv_variable('surface_backwards_scattering_coefficient_of_radar_wave')]   
```

**Comment by akorosov** [comment]
Parameter has fields:
standard_name, short_name, units. 

The source of data in the Parameter tabel in geospaas is two pythesint lists:
get_wkv_variable_list
get_cf_standard_name_list

Therefore get_parameter (or get_geospaas_parameter) should return either get_wkv_variable() or get_cf_standard_name() depending on which one succeeds.

**Comment by aanersc** [comment]
@akorosov 
this part of code is ready. The remaining should be modified in the harvesting reop.

**Comment by aanersc** [comment]
the regex should become more generic!
